### PR TITLE
➕ Add storybook

### PR DESCRIPTION
**Pull request by sweisz**
- `npx sb init`
- Remove example stories folder
- Create components folder with example Button component
- Set stories folder in .storybook/main.js
- Load example component in pages/index.tsx
- Ignore /storybook-static
- Add .eslintignore

### CODE REVIEW

**Review by RonjaMeinecke — APPROVED** [review]
GJ🚀

**Review by mrana17 — CHANGES_REQUESTED** [review]
You missed out the Home.module.css changes! 😱

**Review by christophvogel — APPROVED** [review]
GJ 👍

**Comment by sweisz** [comment]
> You missed out the Home.module.css changes! 😱

Fixed :)

**Pull request merged**
